name: nWorld
description: nWorld
version: ${project.version}
main: works.akus.world.World

api-version: 1.19

depend:
  - nMauris
  - nSocial
  - ProtocolLib

commands:
  camp:
    usage: /camp (target)
    description: Teleports target to the camp