name: nMauris
description: nMauris
version: ${project.version}
main: works.akus.mauris.Mauris

depend: [ ProtocolLib ]

commands:
  mauris:
    usage: /mauris
    description: General command for nMauris

api-version: 1.19